before_build:
    - dotnet restore
build_script:
    - dotnet build src/Aodag.BankAccountTutorial
test_script:
    - dotnet test test/Aodag.BankAccountTutorial.Test
after_test:
    - ps: $timestamp = Get-Date -Format "yyyyMMddHHmmss"
    - ps: dotnet pack -c Release src/Aodag.BankAccountTutorial --version-suffix $timestamp
artifacts:
    - path: '**\*.nupkg'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true